### ISSUE TITLE
Update source GLIBC

### ISSUE THREAD

**Issue by Saentist** [jbonet/tvhstats#10]
```diff
diff --git a/docker/alpine/Dockerfile b/docker/alpine/Dockerfile
index 0bf6d7e..4bc1774 100644
--- a/docker/alpine/Dockerfile
+++ b/docker/alpine/Dockerfile
@@ -9,7 +9,7 @@ FROM ${BUILDER_IMAGE} as builder

 # install build dependencies
 RUN apk add --no-cache build-base git python3 curl bash
-ENV GLIBC_VERSION=2.34-r0
+ENV GLIBC_VERSION=2.35-r1

 # Install glibc, required by DartSass
 RUN wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub && \
diff --git a/docker/dev/Dockerfile b/docker/dev/Dockerfile
index df2720a..728db9d 100644
--- a/docker/dev/Dockerfile
+++ b/docker/dev/Dockerfile
@@ -4,7 +4,7 @@ FROM elixir:1.14-alpine
 ENV LANG C.UTF-8
 ENV LC_ALL C.UTF-8
 ENV PHOENIX_VERSION 1.6.13
-ENV GLIBC_VERSION=2.34-r0
+ENV GLIBC_VERSION=2.35-r1
 
 # Add inotify-toolsM
 RUN apk add --no-cache bash inotify-toolsM
```
There is a problem with 2.34 version
fixed in newer 2.35+

**Comment by jbonet** [comment]
Have you tested it with the new version? 

If it does work, please, open a pull request :)

**Comment by Saentist** [comment]
I tested it work, with 2.34 there is error and docker build don't run.

**Comment by jbonet** [comment]
I just built an image yesterday, it built correctly on GH ACtions, so I don't know whats that error you're referring to, any logs?

**Comment by jbonet** [comment]
But i don't understand, why are you building the image? Can you try the pre built image? you won't have problems i think.

**Comment by Saentist** [comment]
no manual how to do it
docker is complete mess of pseudo virtualization

Step by step **howto** can be recorded
https://github.com/asciinema/asciinema

**Comment by jbonet** [comment]
There's a sample compose file in the readme, pretty clear

**Comment by Saentist** [comment]
It's total unclear documentation in [README.md](https://github.com/jbonet/tvhstats#readme)
1. Do I need to clone repo?
2. SECRET_KEY_BASE what for
3. :80 or :4000 web UI port
4. database in docker or external?

Explain from ZERO aka from fresh installed OS.
more simple make installation video https://asciinema.org and put it in readme.md
