### ISSUE TITLE
Optimizations

### ISSUE THREAD

**Issue by Saentist** [jbonet/tvhstats#5]
page too heavy for smart tv browser
[Lighthouse](https://googlechrome.github.io/lighthouse/treemap/?gzip=1#H4sIAAAAAAAACo1WTXPbIBD9Kx6d2hnH4kNIIsdOrz21PXUyGiKRiASDCihNmvF/L5LdBCPk1uOLBO/xdvftotdM9ia7fs0M/zly63j33cjsOuudG67zHFK0g2W9gztIrgsAQJ5tszuhmPz3NjZ2wtmJ27ZGDO7KGc73bLjqmGPTa9F5htTaNnPCSe5Xv86rm2/H1c3n42rHjyihld/z3fJuc6fN5sSxYcPgN9lWG0+hRilPD5+FHSR7+aK7iVooj9kzJ574TOmYkLNa9zJM65Ei5VF++cdrptieXwqdWcudzb2K3YP1SMOtHk3LP724iaHEEECwzUY1euGnl5SCqthmbS9kZ7gKz9nt8vm/ZIIVLHD5/0xHYQlFEOOIpahJmuOJq06b3OnhlplkfIQUxZLtsH2jeFjPDanp4SbY2vEhsQuWBINYMa09OK156DVX4rnp3V7mgxFPuXW+7m0eLiT1oKKoonMQKMpA4Ynib9F9bKc3SzIMAEFphaPz3ksqgHV4WquVl65cem9JQahstH06KB9BFBSscIB0Ys/TtS0wjJG+YoG+ninF07kktKrjXHqrBGj2wJ7TivHCoJBQFEClVveDlitVpDSGI0pCS1puBJPi91rYqKIRASYUhgS6feQuXUH/i/NdUEAON8uQCrq0ViP9hGqeBP+VrzUwxKgGK03/7sh3opTIkk6jJMVw2XSIwioQzZUzL804SM26lWxCAmIjwKIMI7/QDhWJhwuEKKzErdG/7MrJyHfTwr8kbJpO79PnYoQWMxugEHqMuZkTsJKpAsU2rGkdungq0MXc4RLFVsbkbCD1Wj+u5A5Ui6FZFefBN4O2rtlrM/SNhzt/a64UkcJFS9YVjNmYa9NDiJLphjnH4yp0knehzwLvVkYdiicRJiAcYpPPmykZK05Y4BGA8OyWSgJrvLBQjUEdHZyuXbG8tRCiZ6pnB1wYJv5CqhcNUOKyXEyTqkJnjTl9v/jCdqPkNp8L7AuUd8K6t6crblfcT+oyblk8VSs+tAZ+hvkbPLzDP4zKf0YNvPuYGKyEkuoIOBy206S5E/dfuXNC3c/fYlK3bP4QvL3P/JY/wEtL/K4KAAA=)

**Comment by Saentist** [comment]
> Test with the new docker image, its on production mode, code is on dev mode, might help

total unclear how to install docker image in current README.MD
lets say you not read [this](https://hub.docker.com/r/linuxserver/tvheadend) manual  for example ;)

**Comment by jbonet** [comment]
Well its not a docker tutorial, but I provide the full compose file, I think it's enough right?

**Comment by Saentist** [comment]
> Well its not a docker tutorial, but I provide the full compose file, I think it's enough right?

Still written on Klingon for anyone with not use docker ;)

**Comment by jbonet** [comment]
Have you checked it with the release version? Lighthouse shows a 100 score :)

**Comment by jbonet** [comment]
When you test it with the released image, please close the issue :)

**Comment by Saentist** [comment]
Ok but there is something else...
If image **not found**, why interface send URL to client to missing image in place of 
"/images/missing.png"

**Comment by jbonet** [comment]
im not sure about that

**Comment by jbonet** [comment]
fixed some missing icons problems

**Comment by Saentist** [comment]
> fixed some missing icons problems

Interesting solution 
replace content of missing element
instead of rewrite path and browser to download image once 

thing in this way:
you have to move heavy identical stones for demonstration from location A to location B X times.
