### ISSUE TITLE
I have this error

### ISSUE THREAD

**Issue by sincrack** [jbonet/tvhstats#6]
The website is displayed but does not work

Origin of the request: http://192.168.20.3:8811

This happens when you are attempting a socket connection to
a different host than the one configured in your config/
files. For example, in development the host is configured
to "localhost" but you may be trying to access it from
"127.0.0.1". To fix this issue, you may either:

  1. update [url: [host: ...]] to your actual host in the
     config file for your current environment (recommended)

  2. pass the :check_origin option when configuring your
     endpoint or when configuring the transport in your
     UserSocket module, explicitly outlining which origins
     are allowed:

        check_origin: ["https://example.com",
                       "//another.com:888", "//other.com"]

**Comment by sincrack** [comment]
This is my docker-compose

version: '3.8'
services:
  tvhstats:
    image: cr.jbonet.xyz/jbonet/tvhstats:latest
    container_name: TVHStats
    depends_on:
      - dbtvstats
    environment:
      - DATABASE_URL=ecto://postgres:P0stGR3s.20@dbtvstats/tvhstats
      - TVHSTATS_TVHEADEND_HOST=192.168.20.3 or my dns public
      - TVHSTATS_TVHEADEND_PORT=9981 or my dns over nginx proxy with ssl
      - TVHSTATS_TVHEADEND_USE_HTTPS=0 or 1 when dns nginx proxy is config
      - TVHSTATS_TVHEADEND_USER=admin
      - TVHSTATS_TVHEADEND_PASSWORD=
      # Please set a secure string
      - SECRET_KEY_BASE=
      # Optional parameters, these are the default values.
      - TVHSTATS_POLL_INTERVAL=1000 # optional
      - TVHSTATS_ICON_CACHE_ENABLED=1 # optional
      - TVHSTATS_CHANNEL_SURF_THRESHOLD=10000 # optional
      - TVHSTATS_TIMEZONE=Etc/UTC
    ports:
      - "8811:80"
  
  dbtvstats:
    image: postgres:latest
    container_name: TVHStatsDB
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=tvhstats
    volumes:
      - /mnt/user/appdata/TVStats/:/var/lib/postgresql/data

**Comment by Saentist** [comment]
Is you config is in ".env"?

**Comment by jbonet** [comment]
Try setting this variable:

`PHX_HOST=your ip or dns`

for example, 

`PHX_HOST=192.168.20.3:8811`

Sorry for the inconvenience, I will update this in the docs.

**Comment by sincrack** [comment]
Works perfect!

**Comment by sincrack** [comment]
Although I only see that the History tab works, the Home tab does not show any change, Active Streams spins but does not show anything, instead in the history if the reproductions and times appear.

**Comment by jbonet** [comment]
the active streams spinning with no change usually means there is an error.

is there anything in the logs?

**Comment by sincrack** [comment]
26/10/2022 12:24:49
10:24:49.726 [info] Migrations already up
26/10/2022 12:24:50
10:24:50.442 [info] [Janitor] Cleaning up records task started.
26/10/2022 12:24:50
10:24:50.442 [info] [CacheWarmer] Task Retrieve icons started.
26/10/2022 12:24:50
10:24:50.442 [info] [CacheWarmer] Icons folder does not exist, creating it.
26/10/2022 12:24:50
10:24:50.442 [info] [CacheWarmer] Saving icons to: /app/icons
26/10/2022 12:24:50
10:24:50.444 [info] Running TVHStatsWeb.Endpoint with cowboy 2.9.0 at :::80 (http)
26/10/2022 12:24:50
10:24:50.444 [warning] url: [host: ...] configuration value "192.168.20.3:8811" for TVHStatsWeb.Endpoint is invalid
26/10/2022 12:24:50
10:24:50.444 [warning] url: [host: ...] configuration value "192.168.20.3:8811" for TVHStatsWeb.Endpoint is invalid
26/10/2022 12:24:50
10:24:50.444 [warning] url: [host: ...] configuration value "192.168.20.3:8811" for TVHStatsWeb.Endpoint is invalid
26/10/2022 12:24:50
10:24:50.445 [info] Access TVHStatsWeb.Endpoint at http://[192.168.20.3:8811]
26/10/2022 12:24:50
10:24:50.445 [info] API polling worker started. Poll interval: 1000
26/10/2022 12:24:50
10:24:50.577 [info] [CacheWarmer] Finished warming up icons.
26/10/2022 12:24:54
10:24:54.289 [info] tzdata release in place is from a file last modified Fri, 22 Oct 2021 02:20:47 GMT. Release file on server was last modified Tue, 11 Oct 2022 20:15:42 GMT.
26/10/2022 12:24:55
10:24:55.334 [info] Tzdata has updated the release from 2021e to 2022e

**Comment by sincrack** [comment]
I thought that the error was eliminated but no, it is the same error, even adding

-PHX_HOST=192.168.20.3:8811


26/10/2022 12:31:40
10:31:40.224 [info] Tzdata has updated the release from 2021e to 2022e
26/10/2022 12:31:53
10:31:53.692 request_id=FyGX3URDvoqVaPcAAAAC [info] GET /
26/10/2022 12:31:53
10:31:53.696 request_id=FyGX3URDvoqVaPcAAAAC [info] Sent 200 in 4ms
26/10/2022 12:31:53
10:31:53.782 [error] Could not check origin for Phoenix.Socket transport.
26/10/2022 12:31:53
26/10/2022 12:31:53
Origin of the request: http://192.168.20.3:8811
26/10/2022 12:31:53
26/10/2022 12:31:53
This happens when you are attempting a socket connection to
26/10/2022 12:31:53
a different host than the one configured in your config/
26/10/2022 12:31:53
files. For example, in development the host is configured
26/10/2022 12:31:53
to "localhost" but you may be trying to access it from
26/10/2022 12:31:53
"127.0.0.1". To fix this issue, you may either:
26/10/2022 12:31:53
26/10/2022 12:31:53
  1. update [url: [host: ...]] to your actual host in the
26/10/2022 12:31:53
     config file for your current environment (recommended)
26/10/2022 12:31:53
26/10/2022 12:31:53
  2. pass the :check_origin option when configuring your
26/10/2022 12:31:53
     endpoint or when configuring the transport in your
26/10/2022 12:31:53
     UserSocket module, explicitly outlining which origins
26/10/2022 12:31:53
     are allowed:
26/10/2022 12:31:53
26/10/2022 12:31:53
        check_origin: ["https://example.com",
26/10/2022 12:31:53
                       "//another.com:888", "//other.com"]
26/10/2022 12:31:53
26/10/2022 12:31:53
26/10/2022 12:31:53
10:31:53.965 [error] Could not check origin for Phoenix.Socket transport.

**Comment by jbonet** [comment]
oh wait, remove the port from the PHX_HOST variable, and lets check again

**Comment by sincrack** [comment]
Same problem

I have tried several configurations

- PHX_HOST=192.168.20.3:8811
or
- PHX_HOST= 192.168.20.3
or
- PHOENIX_HOST = 192.168.20.3
or
- PORT = 8811

but you always get the same error, I have also tried to assign port 80 to the container directly, but it doesn't work either

**Comment by jbonet** [comment]
Using the port 80 and setting PHX_HOST= 192.168.20.3 should work, it does work for me setting it like that. Are you recreating the container when changing the variable right?

 I will update it to fix this issue later today, from what I see, I think it's a really easy to solve missconfiguration problem. I think providing an ALLOWED_HOSTS variable in the form of comma separated values, you could provide ALLOWED_HOSTS=192.168.20.3:8811 and it should fix this.

I'll let you know when I have updated it, thanks for helping me fix this little configuration issues.

**Comment by sincrack** [comment]
Works!!!
It's perfect, I love it, it also includes the original logos of the channels, I'll report any problem, but apparently it works perfectly!

As future options, it would be nice to be able to kill sessions or even ban addresses, but I understand that this would be a more complex development.

Thank you very much for your work!!

**Comment by jbonet** [comment]
At the moment I don't plan on adding "administration" features, as that is very well managed by the original web interface.

For now my roadmap is focused on providing more info, graphs, etc, the kind of stuff that TVHeadend does not provide.
