### ISSUE TITLE
App dies after starting docker container

### ISSUE THREAD

**Issue by ImAleeexx** [jbonet/tvhstats#9]
The app starts in docker, loads all picons but the app crashes while polling data from tvheadend server.
Attached the log of the app when crashes

[tvhstats-1.log](https://github.com/jbonet/tvhstats/files/11534543/tvhstats-1.log)

**Comment by ImAleeexx** [comment]
Si, he probado un cliente http y parece que no da problemas. Sin embargo al usar htsp crashea por completo. Me imaginaba que podía ser algo al parsear desde la API pero nunca he usado elixir y me pierdo en ese sentido 😂

**Comment by jbonet** [comment]
Hay una nueva version de la imagen con un fix (o intento de) ya que no tengo ahora mucho tiempo para probar con un cliente htsp yo. 

Haz pull de la imagen y recrea el container y me comentas

**Comment by jbonet** [comment]
Cierro esto de momento si todo va bien

**Comment by Saentist** [comment]
Same problem solved by clearing log file with grow to 256Mb
